version: "3.9"
services:
  api-server:
    container_name: shortener-service
    build:
      context: .
      dockerfile: service.Dockerfile
    networks:
      - shortener-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres?currentSchema=short
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: postgres-db
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - shortener-network
    environment:
      - POSTGRES_PASSWORD=shortener-password
    ports:
      - '5432:5432'
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

networks:
  shortener-network: